### ISSUE TITLE
Question about running the scDECAF

### ISSUE THREAD

**Issue by NianzhenGu** [DavisLaboratory/scDECAF#2] opened 2024-01-02 14:35 UTC
Hi! I'm working on a single-cell RNA project that compares single-cell transcriptomic data of embryonic and adult mouse colons to identify embryonic-specific gene signatures and use these genes to score colon cancer single-cell data. I find the scDECAF algorithm is suitable for this project. 

I have some problems understanding the inputs to the algorithm in the **Quick Start** part. 

- For the variable x, can I put the SingleCellExperiment object?
- I don't know the meaning of `geneset` and the `HM_geneset`. Does the `HM_geneset` represent the human geneset that can be downloaded online? How about the mouse geneset?

What I have now is the gene signature, a vector of gene ids, like "ENSMUSG00000031957" "ENSMUSG00000069893" "ENSMUSG00000055827"...; the data I want to score: a SingleCellExperiment object; a list of highly variable genes (hvg).

Very much appreciate it if you could give me some instructions! Thanks!

**Comment by soroorh** [comment] 2024-01-02 14:57
Hi ! thank you for using the issue tracker!
- we only support standard matrices atm, so you'd have to supply the matrix of normalised expression values of hvg genes
- `HM_geneset`, or the input to `genesetlist` in general in `pruneGenesets()`, is a list of gene sets i.e. each element of the list is a list of genes (names or ids depends on row names of `x`). This is the set of all possible gene sets one is interested, and must consist of more than one gene set (say C2 collection from MSigDB).  The name was selected based on our application (we actually meant Hallmark gene sets), and it does not imply the species. I encourage you to look up the documentation for any of the functions of interest by installing the packages and running `?functionname`

The vector space representation computed by scDECAF requires more than one gene signature. So, i'd recommend you consider adding other gene sets to run the model. For your project, for example, differentially expressed genes in differentially abundant neighbourhoods which you can get from miloDE will provide you with sufficient number of gene sets to use as input to scDECAF.

Link to miloDE https://github.com/MarioniLab/miloDE

Hope this helps.

**Comment by NianzhenGu** [comment] 2024-01-02 15:16
So for example, if I have two gene signatures, s1 = [a, b, c], s2 = [d, e, f]. I can create a geneset like [s1, s2]. Then I run the `pruneGenesets()` and `genesets2ids()` before the` scDECAF()` right?

**Comment by soroorh** [comment] 2024-01-02 15:26
so, the `genesetlist` has to be a named list. so i suggest

```
gslist = list()
gslist[['gs1']] <- s1
gslist[['gs2']] <- s2
```
As i mentioned, due to nature of the model we generally need larger than 2 gene sets. you got the order of running the functions correctly, but if your full geneset list has less than 10 gene sets, pruning via `pruneGenesets ()` might not be required. Hence why i suggested obtaining additional gene sets from miloDE analysis, for example.

I suggest you also checkout our tutorials from the reproducibility repo
https://github.com/DavisLaboratory/scDECAF-reproducibility/blob/master/kang_pbmc/kang_pbmc.ipynb
https://github.com/DavisLaboratory/scDECAF-reproducibility/blob/master/cite_pbmc/TotalVI_scDECAF_analysis-addMilo.ipynb

Hope this helps

**Comment by NianzhenGu** [comment] 2024-01-02 15:40
Great! Thanks for your suggestion! I will try it in the coming days.

**Comment by NianzhenGu** [comment] 2024-01-05 05:12
Hi! I still have a problem. The picture shows my command of running the `scDECAF`. I'm not sure what should I use for the `embedding`. 
<img width="751" alt="Screenshot 2024-01-05 at 12 57 06 PM" src="https://github.com/DavisLaboratory/scDECAF/assets/145458678/15c920eb-4319-4bbf-9222-dad096443fd5">

The rest data: `merged_counts` is my original data with rows are genes and columns are samples. The dim of this data is 25904 x 4.
<img width="815" alt="merged_counts" src="https://github.com/DavisLaboratory/scDECAF/assets/145458678/d808ff5a-50e0-4a53-8df3-b2faf56857f1">

`target` is the result obtained from `genesets2ids()` where rows are genes and columns are genesets. The dim of this data is 106 x 8.
<img width="946" alt="targert" src="https://github.com/DavisLaboratory/scDECAF/assets/145458678/462617b1-0816-4622-b921-4e87146ed0a7">

`hvg_union` is the list of hvg, the length is 8698.
<img width="977" alt="hvg_union" src="https://github.com/DavisLaboratory/scDECAF/assets/145458678/8bb3ddf9-23ab-40a7-a973-17ad4d008d28">

For the `embedding = reducedDims(tumor_sce)[["UMAP"]]`, the `tumor_sce` is the SingleCellExperiment object. I'm not sure whether my inputs are correct for the data I showed above. 

Appreciate it if you could find the problem! Thanks!

**Comment by soroorh** [comment] 2024-01-05 05:43
Hi. so the error is suggesting that `dim(embedding)!= dim(merged_counts)`. Can you pls verify that? also, i suggest you use log normalised gene expression rather than raw counts, i.e. scTransformed data. 

For embedding, you can use umap as you're doing here, but can also consider any other embedding (PCA, PHATE etc with > 2 dimensions).  

Hope this helps!

**Comment by NianzhenGu** [comment] 2024-01-05 06:22
The `merged_counts` is log normalized. I tried the PCA but still got the same error:

<img width="495" alt="Screenshot 2024-01-05 at 2 21 10 PM" src="https://github.com/DavisLaboratory/scDECAF/assets/145458678/01e0850c-e4f0-47a0-8227-ab5a6df6fad6">


<img width="633" alt="Screenshot 2024-01-05 at 2 19 09 PM" src="https://github.com/DavisLaboratory/scDECAF/assets/145458678/533f5dd7-f387-4dc6-9ca3-a276d4788370">

**Comment by soroorh** [comment] 2024-01-05 06:43
ok - thanks. Are the row names set for the embedding matrix? scDECAF at some point matches column names in `merged_counts` with row names in the embedding. hopefully that fixes?

**Comment by NianzhenGu** [comment] 2024-01-05 06:51
Sorry, I'm not sure about what you mean. The row name of embedding is the gene name and the column name is PC1, PC2, PC3, PC4. The row name of `merged_counts` is the gene name with the same order and the column name is four sample names.

**Comment by soroorh** [comment] 2024-01-05 06:55
ah then i see what's going wrong. the embedding is a *cell embedding* ie. has dims n_cells x n_D where D is the dimension in the dimension reduction space.  Whereas you are providing a gene embedding. Your initial code was correct because you had `reducedDims(tumor_sce)[["UMAP"]]`. Please just check the row names there and verify `nrow(educedDims(tumor_sce)[["UMAP"]]) == ncol(merged_counts)`.

**Comment by NianzhenGu** [comment] 2024-01-05 07:01
So the `merged_count` should be n_gene x n_cells and the embedding should be n_cells x n_D. But the dim(`merged_count`) will not be equal to dim(embedding)? Also, the column name of `merged_count` should be the same as the row name of embedding, which is the cell name, right?

**Comment by soroorh** [comment] 2024-01-05 07:04
correct. `dim(embedding)!= dim(merged_counts)` is always true and i actually meant the error is suggesting `nrow(embedding)!= ncol(merged_counts)`, or that row names are not set in `embedding`. Apologies for confusion.

**Comment by soroorh** [comment] 2024-01-05 07:06
also since you only have 8 gene sets, `k` should be <8 (you have 10 now). I also updated README with more specifications.

**Comment by NianzhenGu** [comment] 2024-01-05 07:06
Thanks! Will try it.

**Comment by Jade0904** [comment] 2024-01-05 14:03
Hi, I'm NianzhenGu's teammate. I still cannot run scDECAF successfully. Here's the error:

![image](https://github.com/DavisLaboratory/scDECAF/assets/145372425/2e3b9c25-9f65-43ad-b527-3e28dd8e5673)

"merged_logcounts" was defined by "merged_logcounts <- logcounts(merged_sce)" and the logcounts assay was generated by "merged_sce <- logNormCounts(merged_sce)".

"target" was defined by "target <- genesets2ids(merged_logcounts, gene_signature)", where "gene_signature" was a list of geneset, as below:

![image](https://github.com/DavisLaboratory/scDECAF/assets/145372425/e684ba21-bd4c-4cba-8e22-cd414fe22bf1)

hvg_union was a vector of highly variable genes we chose.

Reduced dimensions were generated by:
merged_sce <- runPCA(merged_sce)
merged_sce <- runUMAP(merged_sce, dimred = "PCA")
I tried both of them (UMAP and PCA) in scDECAF() but it threw the same error.

Do you have any idea about what could possibly be the problems? Thanks a lot :)

**Comment by soroorh** [comment] 2024-01-05 14:07
Hey :).
Since data is log-transformed, please set `standardize=FALSE`, as per example code on README. Hope this helps.

**Comment by Jade0904** [comment] 2024-01-05 14:16
> Hey :). Since data is log-transformed, please set `standardize=FALSE`, as per example code on README. Hope this helps.

Yes, it worked! Thank you so much for your help!

**Comment by soroorh** [comment] 2024-01-05 14:18
No worries. please close the issue, if this is done!

**Closed as completed** 2024-01-10 13:49 UTC
